package kiosk.order;

import java.util.ArrayList;

import kiosk.restaurant.Food;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Order.java
//  @ Date : 2020-05-07
//  @ Author : 
//
//




public class Order {
	private ArrayList<Food> list;
	private int orderNum;
	private int totalPrice;
	private String id;
	private String date;
	private boolean payment;
	public Order() {
		list = new ArrayList<Food>();
	}
	public Order( int orderNum, int totalPrice, String id, String date, boolean payment) {
		list = new ArrayList<Food>();
		this.orderNum = orderNum;
		this.totalPrice = totalPrice;
		this.id = id;
		this.date = date;
		this.payment = payment;
	}
	public ArrayList<Food> getList() {
		return list;
	}
	public void setList(ArrayList<Food> list) {
		this.list = list;
	}
	public int getOrderNum() {
		return orderNum;
	}
	public void setOrderNum(int orderNum) {
		this.orderNum = orderNum;
	}
	public int getTotalPrice() {
		return totalPrice;
	}
	public void setTotalPrice(int totalPrice) {
		this.totalPrice = totalPrice;
	}
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public String getDate() {
		return date;
	}
	public void setDate(String date) {
		this.date = date;
	}
	public boolean getPayment() {
		return payment;
	}
	public void setPayment(boolean payment) {
		this.payment = payment;
	}
}
