package kiosk.order;

import java.util.ArrayList;
import java.util.Scanner;

import kiosk.restaurant.Food;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : OrderService.java
//  @ Date : 2020-05-07
//  @ Author : 
//
//




public class OrderService {
	private Dao dao;
	private Order order;
	
	public OrderService() {
		this.dao = new OrderDaoImpl();
	}
	
	public void Order() {
		this.order = new Order();
	}
	
	public int itemAdd(Scanner scan) {
		Food f = selectByNum(scan);
		System.out.println(f.getName());
		boolean t = order.getList().add(f);
		System.out.println(order.getList().get(0).getName());
		if(t) return 1;
		else return 0;
	}
	
	public int itemSub(Scanner scan) {
		printList();
		System.out.println("취소할 메뉴 : ");
		int num = scan.nextInt();
		boolean t = order.getList().remove(num) != null;
		if(t) return 1;
		else return 0;
	}
	
	public void printList() {
		System.out.println("----주문 목록----");
		ArrayList<Food> list = order.getList();
		for(Food a : list) {
			System.out.println("번호 : " + list.indexOf(a) + "이름 : " +  a.getName() +"가격 : " + a.getPrice() );
		}
	
	}
	
	public Food selectByNum(Scanner scan) {
		ArrayList<Food> list = dao.foodSelectAll();
		System.out.println("---------메뉴----------");
		System.out.println("번호\t\t\t이름\t\t\t\t가격");
		for(Food a : list) {
			System.out.print( a.getNum() + "\t\t");
			System.out.printf("%10s", a.getName());
			System.out.println("\t\t\t\t" + a.getPrice());
		}
		System.out.print("메뉴 : ");
		int num = scan.nextInt();
		Food f = dao.foodSelect(num);
		
		return f;
	}
	
	public int itemUpdate() {
		return 0;
	}
	
	public void payment() {
	
	}
	
	public void printPayList() {
	
	}
}
